const animeSeries = [
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-17T08:17:20.574Z',

  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'One Piece',
    url: 'https://static.wikia.nocookie.net/bf9e36bc-c8b7-4ccb-8f3e-e4f958cb86a0/scale-to-width-down/800',
    total_votes: 980,
    body: 'One Piece is a long-running adventure series set in a world of pirates and treasures. It follows Monkey D. Luffy and his crew, the Straw Hat Pirates, as they sail the seas in search of the ultimate treasure, the One Piece. Along the way, they encounter powerful foes, form alliances, and uncover the mysteries of the world.',
    createdAt: '2023-06-12T08:17:20.574Z',

  },
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'One Piece',
    url: 'https://static.wikia.nocookie.net/bf9e36bc-c8b7-4ccb-8f3e-e4f958cb86a0/scale-to-width-down/800',
    total_votes: 980,
    body: 'One Piece is a long-running adventure series set in a world of pirates and treasures. It follows Monkey D. Luffy and his crew, the Straw Hat Pirates, as they sail the seas in search of the ultimate treasure, the One Piece. Along the way, they encounter powerful foes, form alliances, and uncover the mysteries of the world.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Cowboy Bebop',
    url: 'https://www.denofgeek.com/wp-content/uploads/2021/09/cowboy-bebop-01.jpg',
    total_votes: 830,
    body: 'Cowboy Bebop is a stylish space western series following the adventures of a bounty hunter named Spike Spiegel and his diverse crew of misfits aboard the spaceship Bebop. They travel through space, pursuing dangerous criminals and confronting their own troubled pasts. The series is known for its unique blend of action, jazz music, and deep character development.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Fullmetal Alchemist: Brotherhood',
    url: 'https://cdn.myanimelist.net/images/anime/5/47421.jpg',
    total_votes: 920,
    body: 'Fullmetal Alchemist: Brotherhood is a gripping fantasy series set in a world where alchemy is a powerful tool. The story follows the Elric brothers, Edward and Alphonse, who seek the Philosopher\'s Stone to restore their bodies after a disastrous alchemical experiment. Their journey takes them on a path filled with political intrigue, moral dilemmas, and supernatural encounters.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Death Note',
    url: 'https://cdn.myanimelist.net/images/anime/5/62847.jpg',
    total_votes: 880,
    body: 'Death Note is a psychological thriller that revolves around a high school student named Light Yagami, who discovers a supernatural notebook called the Death Note. With the power to kill anyone by writing their name in it, Light takes on the role of a self-proclaimed "justice" and tries to cleanse the world of criminals. However, his actions attract the attention of a brilliant detective known as L, leading to a thrilling game of cat and mouse.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-15T08:17:20.574Z',

  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'One Piece',
    url: 'https://static.wikia.nocookie.net/bf9e36bc-c8b7-4ccb-8f3e-e4f958cb86a0/scale-to-width-down/800',
    total_votes: 980,
    body: 'One Piece is a long-running adventure series set in a world of pirates and treasures. It follows Monkey D. Luffy and his crew, the Straw Hat Pirates, as they sail the seas in search of the ultimate treasure, the One Piece. Along the way, they encounter powerful foes, form alliances, and uncover the mysteries of the world.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Cowboy Bebop',
    url: 'https://www.denofgeek.com/wp-content/uploads/2021/09/cowboy-bebop-01.jpg',
    total_votes: 830,
    body: 'Cowboy Bebop is a stylish space western series following the adventures of a bounty hunter named Spike Spiegel and his diverse crew of misfits aboard the spaceship Bebop. They travel through space, pursuing dangerous criminals and confronting their own troubled pasts. The series is known for its unique blend of action, jazz music, and deep character development.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Fullmetal Alchemist: Brotherhood',
    url: 'https://cdn.myanimelist.net/images/anime/5/47421.jpg',
    total_votes: 920,
    body: 'Fullmetal Alchemist: Brotherhood is a gripping fantasy series set in a world where alchemy is a powerful tool. The story follows the Elric brothers, Edward and Alphonse, who seek the Philosopher\'s Stone to restore their bodies after a disastrous alchemical experiment. Their journey takes them on a path filled with political intrigue, moral dilemmas, and supernatural encounters.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Death Note',
    url: 'https://cdn.myanimelist.net/images/anime/5/62847.jpg',
    total_votes: 880,
    body: 'Death Note is a psychological thriller that revolves around a high school student named Light Yagami, who discovers a supernatural notebook called the Death Note. With the power to kill anyone by writing their name in it, Light takes on the role of a self-proclaimed "justice" and tries to cleanse the world of criminals. However, his actions attract the attention of a brilliant detective known as L, leading to a thrilling game of cat and mouse.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'One Piece',
    url: 'https://static.wikia.nocookie.net/bf9e36bc-c8b7-4ccb-8f3e-e4f958cb86a0/scale-to-width-down/800',
    total_votes: 980,
    body: 'One Piece is a long-running adventure series set in a world of pirates and treasures. It follows Monkey D. Luffy and his crew, the Straw Hat Pirates, as they sail the seas in search of the ultimate treasure, the One Piece. Along the way, they encounter powerful foes, form alliances, and uncover the mysteries of the world.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'Cowboy Bebop',
    url: 'https://www.denofgeek.com/wp-content/uploads/2021/09/cowboy-bebop-01.jpg',
    total_votes: 830,
    body: 'Cowboy Bebop is a stylish space western series following the adventures of a bounty hunter named Spike Spiegel and his diverse crew of misfits aboard the spaceship Bebop. They travel through space, pursuing dangerous criminals and confronting their own troubled pasts. The series is known for its unique blend of action, jazz music, and deep character development.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'Fullmetal Alchemist: Brotherhood',
    url: 'https://cdn.myanimelist.net/images/anime/5/47421.jpg',
    total_votes: 920,
    body: 'Fullmetal Alchemist: Brotherhood is a gripping fantasy series set in a world where alchemy is a powerful tool. The story follows the Elric brothers, Edward and Alphonse, who seek the Philosopher\'s Stone to restore their bodies after a disastrous alchemical experiment. Their journey takes them on a path filled with political intrigue, moral dilemmas, and supernatural encounters.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'Death Note',
    url: 'https://cdn.myanimelist.net/images/anime/5/62847.jpg',
    total_votes: 880,
    body: 'Death Note is a psychological thriller that revolves around a high school student named Light Yagami, who discovers a supernatural notebook called the Death Note. With the power to kill anyone by writing their name in it, Light takes on the role of a self-proclaimed "justice" and tries to cleanse the world of criminals. However, his actions attract the attention of a brilliant detective known as L, leading to a thrilling game of cat and mouse.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-11T08:17:20.574Z',
  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-16T08:17:20.574Z',
  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-15T08:17:20.574Z',
  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-14T08:17:20.574Z',
  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-12T08:17:20.574Z',
  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
  {
    title: 'Neon Genesis Evangelion',
    url: 'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    total_votes: 720,
    body: 'Neon Genesis Evangelion is a mecha series with psychological and philosophical themes. It follows the story of Shinji Ikari, a teenager who becomes a pilot of a giant bio-machine called an Evangelion. As he battles against monstrous beings known as Angels, Shinji grapples with his own identity and the complexities of human existence.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
  {
    title: 'Haikyuu!!',
    url: 'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    total_votes: 890,
    body: 'Haikyuu!! is a sports anime centered around high school volleyball. The series follows Shōyō Hinata, a determined and energetic student who aspires to become a great volleyball player despite his short stature. Alongside his teammates, Hinata faces various challenges on and off the court as they strive to reach the national championship.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
  {
    title: 'Dragon Ball Z',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/11/dragon-ball-z.png?fit=bounds&width=1280&height=720',
    total_votes: 1000,
    body: 'Dragon Ball Z is an iconic action-packed series that continues the story of Goku, a Saiyan warrior. The series features intense battles against powerful foes, epic transformations, and a colorful cast of characters. As Goku protects the Earth from various threats, he grows stronger and seeks to push his limits.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
  {
    title: 'A Place Further than the Universe',
    url: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/aplacefurther-720x405.jpg?fit=bounds&width=1280&height=720',
    total_votes: 500,
    body: 'A Place Further than the Universe is a heartwarming and inspiring series that follows a group of high school girls on an expedition to Antarctica. Each with their own motivations, they embark on a journey of self-discovery, friendship, and overcoming personal obstacles as they strive to make their dreams a reality.',
    createdAt: '2023-06-17T08:17:20.574Z',
  },
 {
    title: 'Fullmetal Alchemist: Brotherhood',
    url: 'https://cdn.myanimelist.net/images/anime/5/47421.jpg',
    total_votes: 920,
    body: 'Fullmetal Alchemist: Brotherhood is a gripping fantasy series set in a world where alchemy is a powerful tool. The story follows the Elric brothers, Edward and Alphonse, who seek the Philosopher\'s Stone to restore their bodies after a disastrous alchemical experiment. Their journey takes them on a path filled with political intrigue, moral dilemmas, and supernatural encounters.',
    createdAt: '2023-06-18T08:17:20.574Z',
  },
  {
    title: 'Death Note',
    url: 'https://cdn.myanimelist.net/images/anime/5/62847.jpg',
    total_votes: 880,
    body: 'Death Note is a psychological thriller that revolves around a high school student named Light Yagami, who discovers a supernatural notebook called the Death Note. With the power to kill anyone by writing their name in it, Light takes on the role of a self-proclaimed "justice" and tries to cleanse the world of criminals. However, his actions attract the attention of a brilliant detective known as L, leading to a thrilling game of cat and mouse.',
    createdAt: '2023-06-18T08:17:20.574Z',
  },
  {
    title: 'Tokyo Ghoul',
    url: 'https://whatnerd.com/wp-content/uploads/2022/01/best-anime-cops-detectives-and-law-enforcement-organizations-commission-on-counter-ghoul-ccg-doves.jpg',
    total_votes: 800,
    body: 'Tokyo Ghoul is a dark fantasy series set in a world where flesh-eating ghouls exist alongside humans. The story follows Ken Kaneki, a college student who becomes a half-ghoul after a violent encounter. He must navigate the dangerous world of ghouls while struggling to retain his humanity.',
    createdAt: '2023-06-18T08:17:20.574Z',
  },
  {
    title: 'Your Lie in April',
    url: 'https://www.fortressofsolitude.co.za/wp-content/uploads/2023/01/Top-22-Best-Most-Popular-Romance-Anime-Series-To-Date-750x375.jpg',
    total_votes: 950,
    body: 'Your Lie in April is a heartwarming romance series centered around music. It tells the story of Kōsei Arima, a former child prodigy pianist who lost his ability to play after a traumatic event. His life takes a turn when he meets a free-spirited violinist named Kaori Miyazono, who helps him rediscover his passion for music.',
    createdAt: '2023-06-18T08:17:20.574Z',
  },
  {
    title: 'Attack on Titan',
    url: 'https://i2.wp.com/thenerddaily.com/wp-content/uploads/2020/05/8-Anime-Series-Worth-The-Binge-Watch.jpg?resize=770%2C571&ssl=1',
    total_votes: 1000,
    body: 'Attack on Titan is an action-packed series set in a world where humanity is on the brink of extinction due to giant humanoid creatures called Titans. The story follows Eren Yeager and his friends as they join the fight against the Titans and uncover the mysteries surrounding their existence.',
    createdAt: '2023-06-18T08:17:20.574Z',
  },
];

module.exports = animeSeries;

